name: aks-ci-cd

on:
  push:
    branches:
      - master   # o main según tu repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.registry }}.azurecr.io/azure-vote-front:${{ github.sha }} ./azure-vote

      - name: Login to ACR
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > creds.json
          az login --service-principal \
            --username $(jq -r .clientId creds.json) \
            --password $(jq -r .clientSecret creds.json) \
            --tenant $(jq -r .tenantId creds.json)

          az acr login --name ${{ secrets.registry }}

      - name: Push image
        run: |
          docker push ${{ secrets.registry }}.azurecr.io/azure-vote-front:${{ github.sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.resource_group }}
          cluster-name: ${{ secrets.cluster_name }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            azure-vote-all-in-one-redis.yaml
          images: |
            ${{ secrets.registry }}.azurecr.io/azure-vote-front:${{ github.sha }}
