name: build_deploy_aks

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build image in ACR
        run: |
          az acr login --name ${{ secrets.registry }}

          az acr build \
            --registry ${{ secrets.registry }} \
            --image azure-vote-front:${{ github.sha }} \
            ./azure-vote

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.resource_group }}
          cluster-name: ${{ secrets.cluster_name }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            azure-vote-all-in-one-redis.yaml
          images: |
            ${{ secrets.registry }}.azurecr.io/azure-vote-front:${{ github.sha }}
